"""Phase 4 — posting the ledger: the balance proof, validation and atomicity.

Every test here goes through :class:`AccountingService` (the only writer, PART 46) against
the real migrated, seeded database, and then reads the result back with SQL to check what
was actually *stored* rather than what the service says it stored. That distinction is the
whole point of a financial test suite: a service that reports a balanced entry while
writing an unbalanced one would pass a test that only inspected its return value.

Covered here: the balanced/unbalanced matrix, multi-line entries, decimal precision at the
stored scale, accounting dates, reference/document rules, account and currency validation,
branch validation, and transaction atomicity (a failure leaves nothing behind — no entry,
no lines, no cache row, no audit row, no idempotency row).
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal

import pytest
from fastapi.testclient import TestClient

from app.core.audit_actions import AuditAction
from app.core.exceptions import (
    DuplicateResourceError,
    ForbiddenScopeError,
    JournalUnbalancedError,
    PermissionDeniedError,
    ResourceNotFoundError,
    ValidationError,
)
from app.core.money import money_sum
from app.core.permissions import RoleName
from app.services.accounting_service import PostingLine
from tests.accounting_helpers import (
    BASE_CODE,
    World,
    at_utc,
    build_world,
    count,
    entry_row,
    ledger_rows,
    line,
    read,
    run_scenario,
    scalar,
    totals,
    user_id_of,
)

pytestmark = [pytest.mark.integration, pytest.mark.accounting]


def manual_entry(world: World, **overrides: object) -> dict[str, object]:
    """The arguments of a two-line manual adjustment, overridable per test.

    A manual adjustment is the one reference type that may omit its document id, which
    makes it the right vehicle for testing the posting rules themselves without inventing a
    business document.
    """
    arguments: dict[str, object] = {
        "reference_type": "MANUAL_ADJUSTMENT",
        "reference_id": uuid.uuid4(),
        "lines": [
            line(world.account("cash_afn"), debit="1000", currency_id=world.base.id),
            line(world.account("capital"), credit="1000", currency_id=world.base.id),
        ],
        "actor": world.head_actor,
        "branch_id": world.branch_id,
        "description": "Phase 4 posting suite",
    }
    arguments.update(overrides)
    return arguments


class TestBalancedPosting:
    """The happy path, verified in the database and not only in the return value."""

    def test_a_balanced_entry_is_stored_exactly_as_posted(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        reference_id = uuid.uuid4()

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world,
                    reference_id=reference_id,
                    description="Opening the till",
                    transaction_date=at_utc(minutes_ago=30),
                )
            )

        view = run_scenario(main_database, scenario)

        assert view.is_balanced is True
        assert view.total_debit == Decimal("1000")
        assert view.total_credit == Decimal("1000")
        assert view.line_count == 2
        assert view.reference_type == "MANUAL_ADJUSTMENT"
        assert view.reference_id == reference_id
        assert view.branch_id == world.branch_id
        assert view.branch_code == world.branch_code
        assert view.created_by == world.head_user_id
        assert view.created_by_username == "admin"
        assert view.transaction_date.astimezone(dt.UTC).year == dt.datetime.now(tz=dt.UTC).year

        # ... and in the database
        stored = entry_row(main_database, view.id)
        assert stored["reference_id"] == reference_id
        assert stored["branch_id"] == world.branch_id
        assert stored["description"] == "Opening the till"
        rows = ledger_rows(main_database, view.id)
        assert len(rows) == 2
        debit_row = next(row for row in rows if row["account_id"] == world.account("cash_afn"))
        credit_row = next(row for row in rows if row["account_id"] == world.account("capital"))
        assert debit_row["debit"] == Decimal("1000.0000000000")
        assert debit_row["credit"] == Decimal("0E-10")
        assert credit_row["credit"] == Decimal("1000.0000000000")
        # ``foreign_amount`` is generated by PostgreSQL from the pair and the rate.
        assert debit_row["foreign_amount"] == Decimal("1000.0000000000")
        assert credit_row["exchange_rate"] == Decimal("1.0000000000")

    def test_total_debits_equal_total_credits_for_the_whole_ledger(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            for index in range(3):
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=uuid.uuid4(),
                        description=f"Batch {index}",
                        lines=[
                            line(
                                world.account("cash_afn"),
                                debit="10.25",
                                currency_id=world.base.id,
                            ),
                            line(
                                world.account("capital"),
                                credit="10.25",
                                currency_id=world.base.id,
                            ),
                        ],
                    )
                )

        run_scenario(main_database, scenario)
        debit, credit = totals(main_database)
        assert debit == credit

    def test_a_multi_line_entry_is_stored_line_for_line(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """Five lines, two frequencies of the same account, exact totals."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world,
                    reference_id=uuid.uuid4(),
                    lines=[
                        line(world.account("cash_afn"), debit="1500", currency_id=world.base.id),
                        line(
                            world.account("receivable"), debit="250.50", currency_id=world.base.id
                        ),
                        line(world.account("expense"), debit="99.50", currency_id=world.base.id),
                        line(world.account("capital"), credit="1800", currency_id=world.base.id),
                        line(world.account("payable"), credit="50", currency_id=world.base.id),
                    ],
                )
            )

        view = run_scenario(main_database, scenario)
        assert view.line_count == 5
        assert view.total_debit == Decimal("1850.00")
        assert view.total_credit == Decimal("1850.00")
        stored = ledger_rows(main_database, view.id)
        debit = money_sum(Decimal(str(row["debit"])) for row in stored)
        credit = money_sum(Decimal(str(row["credit"])) for row in stored)
        assert debit == Decimal("1850.0000000000")
        assert credit == Decimal("1850.0000000000")
        # No line was dropped, merged or rewritten on the way in.
        assert len({row["account_code"] for row in stored}) == 5

    def test_a_group_of_entries_leaves_the_books_balanced(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            views = []
            for amount in ("1", "0.0000000001", "999999.9999999999"):
                views.append(
                    await service.create_journal_entry(
                        **manual_entry(  # type: ignore[arg-type]
                            world,
                            reference_id=uuid.uuid4(),
                            lines=[
                                line(
                                    world.account("cash_afn"),
                                    debit=amount,
                                    currency_id=world.base.id,
                                ),
                                line(
                                    world.account("capital"),
                                    credit=amount,
                                    currency_id=world.base.id,
                                ),
                            ],
                        )
                    )
                )
            return views

        views = run_scenario(main_database, scenario)
        assert all(view.is_balanced for view in views)
        for view in views:
            assert len(ledger_rows(main_database, view.id)) == 2


class TestUnbalancedAndMalformedEntriesAreRefused:
    """Nothing unbalanced may reach the table — refused before the insert."""

    def test_an_unbalanced_entry_is_refused_and_nothing_is_written(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        reference_id = uuid.uuid4()
        before = count(main_database, "journal_entries")

        async def scenario(service):
            with pytest.raises(JournalUnbalancedError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=reference_id,
                        lines=[
                            line(
                                world.account("cash_afn"), debit="1000", currency_id=world.base.id
                            ),
                            line(
                                world.account("capital"),
                                credit="999.99",
                                currency_id=world.base.id,
                            ),
                        ],
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["difference"] == "0.0100000000"
        assert count(main_database, "journal_entries") == before
        assert (
            count(
                main_database,
                "journal_entries",
                where="reference_id = :reference_id",
                reference_id=reference_id,
            )
            == 0
        )

    @pytest.mark.parametrize(
        ("label", "lines_builder"),
        [
            (
                "debit_only",
                lambda world: [
                    line(world.account("cash_afn"), debit="100", currency_id=world.base.id),
                    line(world.account("capital"), debit="0", currency_id=world.base.id),
                ],
            ),
            (
                "credit_only",
                lambda world: [
                    line(world.account("cash_afn"), credit="100", currency_id=world.base.id),
                    line(world.account("capital"), credit="0", currency_id=world.base.id),
                ],
            ),
            (
                "zero_value",
                lambda world: [
                    line(world.account("cash_afn"), debit="0", currency_id=world.base.id),
                    line(world.account("capital"), credit="0", currency_id=world.base.id),
                ],
            ),
            (
                "negative",
                lambda world: [
                    line(world.account("cash_afn"), debit="-100", currency_id=world.base.id),
                    line(world.account("capital"), credit="-100", currency_id=world.base.id),
                ],
            ),
            (
                "one_line",
                lambda world: [
                    line(world.account("cash_afn"), debit="0", currency_id=world.base.id),
                ],
            ),
            ("empty", lambda _world: []),
            (
                "both_sides_on_one_line",
                lambda world: [
                    line(
                        world.account("cash_afn"),
                        debit="100",
                        credit="100",
                        currency_id=world.base.id,
                    ),
                    line(world.account("capital"), credit="100", currency_id=world.base.id),
                ],
            ),
        ],
    )
    def test_rejected_shapes_never_reach_the_table(
        self,
        api_client: TestClient,
        admin_headers: dict[str, str],
        main_database: str,
        label: str,
        lines_builder: object,
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        reference_id = uuid.uuid4()
        before = count(main_database, "journal_entries")

        async def scenario(service):
            with pytest.raises(JournalUnbalancedError):
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=reference_id,
                        lines=lines_builder(world),  # type: ignore[operator]
                    )
                )

        run_scenario(main_database, scenario)
        assert count(main_database, "journal_entries") == before, label
        assert count(main_database, "journal_lines") == _lines_before(main_database), label

    def test_more_precision_than_the_column_holds_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(
                                world.account("cash_afn"),
                                debit="0.00000000001",
                                currency_id=world.base.id,
                            ),
                            line(
                                world.account("capital"),
                                credit="0.00000000001",
                                currency_id=world.base.id,
                            ),
                        ],
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["fields"][0]["code"] == "not_exact_scale"

    def test_a_float_amount_cannot_enter_the_ledger(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            PostingLine(
                                account_id=world.account("cash_afn"),
                                currency_id=world.base.id,
                                debit=10.25,  # type: ignore[arg-type]
                            ),
                            line(
                                world.account("capital"), credit="10.25", currency_id=world.base.id
                            ),
                        ],
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["fields"][0]["code"] == "not_a_decimal"


class TestPrecisionAtTheStoredScale:
    """NUMERIC(30,10) is the contract; these tests pin both ends of it."""

    def test_the_smallest_storable_amount_survives_a_round_trip(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world,
                    reference_id=uuid.uuid4(),
                    lines=[
                        line(
                            world.account("cash_afn"),
                            debit="0.0000000001",
                            currency_id=world.base.id,
                        ),
                        line(
                            world.account("capital"),
                            credit="0.0000000001",
                            currency_id=world.base.id,
                        ),
                    ],
                )
            )

        view = run_scenario(main_database, scenario)
        assert view.total_debit == Decimal("0.0000000001")
        rows = ledger_rows(main_database, view.id)
        assert max(Decimal(str(row["debit"])) for row in rows) == Decimal("0.0000000001")
        # The wire format is plain fixed point, never an exponent (API_CONTRACT §2).
        assert view.to_payload()["total_debit"] == "0.0000000001"
        assert view.to_payload(with_lines=False)["total_credit"] == "0.0000000001"
        assert all("E" not in str(line.to_payload()["debit"]) for line in view.lines)

    def test_a_twenty_digit_amount_is_posted_without_losing_a_digit(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        huge = "99999999999999999999.9999999998"

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world,
                    reference_id=uuid.uuid4(),
                    lines=[
                        line(world.account("cash_afn"), debit=huge, currency_id=world.base.id),
                        line(world.account("capital"), credit=huge, currency_id=world.base.id),
                    ],
                )
            )

        view = run_scenario(main_database, scenario)
        assert view.total_debit == Decimal(huge)
        rows = ledger_rows(main_database, view.id)
        assert {row["debit"] for row in rows} == {Decimal(huge), Decimal("0E-10")}

    def test_an_amount_beyond_the_column_is_refused_with_a_domain_error(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """A value the column cannot hold is a 422, not an ``InvalidOperation`` (500)."""
        world = build_world(api_client, admin_headers, main_database)
        beyond = "100000000000000000000.0000000000"

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(
                                world.account("cash_afn"), debit=beyond, currency_id=world.base.id
                            ),
                            line(
                                world.account("capital"), credit=beyond, currency_id=world.base.id
                            ),
                        ],
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["fields"][0]["code"] == "over_maximum"

    def test_fractional_amounts_add_up_exactly(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """0.1 + 0.2 = 0.3 — the classic float trap, asserted at the stored scale."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world,
                    reference_id=uuid.uuid4(),
                    lines=[
                        line(world.account("cash_afn"), debit="0.1", currency_id=world.base.id),
                        line(world.account("receivable"), debit="0.2", currency_id=world.base.id),
                        line(world.account("capital"), credit="0.3", currency_id=world.base.id),
                    ],
                )
            )

        view = run_scenario(main_database, scenario)
        assert view.is_balanced is True
        assert view.total_debit == Decimal("0.3")


class TestAccountingDates:
    def test_a_back_dated_entry_keeps_its_date(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """Back-dating is allowed (no period lock in the MVP) and stored verbatim."""
        world = build_world(api_client, admin_headers, main_database)
        moment = at_utc(days_ago=45)

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_id=uuid.uuid4(), transaction_date=moment
                )
            )

        view = run_scenario(main_database, scenario)
        stored = entry_row(main_database, view.id)
        assert stored["transaction_date"].astimezone(dt.UTC) == moment

    def test_a_naive_date_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=uuid.uuid4(),
                        transaction_date=dt.datetime(2026, 1, 1, 10, 0),
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"] == [
            {"field": "transaction_date", "code": "naive"}
        ]

    def test_a_future_date_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=uuid.uuid4(),
                        transaction_date=dt.datetime.now(tz=dt.UTC) + dt.timedelta(days=2),
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"] == [
            {"field": "transaction_date", "code": "future_date"}
        ]

    def test_entries_can_be_queried_by_date_range(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """The date rule is not decoration: reports filter on the stored instant."""
        world = build_world(api_client, admin_headers, main_database)
        old, recent = at_utc(days_ago=10), at_utc(hours_ago=2)

        async def scenario(service):
            first = await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_id=uuid.uuid4(), transaction_date=old
                )
            )
            second = await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_id=uuid.uuid4(), transaction_date=recent
                )
            )
            # A window only this posting can fall into: the branch is shared with every
            # other scenario in the run, so a five-day window would be dominated by their
            # "now" postings and the page would not be about this test at all.
            windowed, total = await service.list_journal_entries(
                actor=world.head_actor,
                branch_id=world.branch_id,
                from_=at_utc(hours_ago=3),
                to=at_utc(hours_ago=1),
                limit=200,
            )
            return first, second, {view.id for view in windowed}, total

        first, second, visible, total = run_scenario(main_database, scenario)
        assert first.id not in visible
        assert second.id in visible
        assert total >= 1
        assert total == len(visible), "the page was truncated by the limit, not by the filter"


class TestReferenceAndDocumentRules:
    def test_a_document_posting_without_its_document_id_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world, reference_type="EXPENSE", reference_id=None
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"] == [
            {"field": "reference_id", "code": "required"}
        ]

    def test_one_document_posts_one_entry(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """``ux_journal_entries_one_per_reference`` is what makes double posting impossible."""
        world = build_world(api_client, admin_headers, main_database)
        reference_id = uuid.uuid4()

        async def scenario(service):
            first = await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_type="EXPENSE", reference_id=reference_id
                )
            )
            with pytest.raises(DuplicateResourceError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_type="EXPENSE",
                        reference_id=reference_id,
                        description="second attempt",
                    )
                )
            return first, refusal.value

        first, refusal = run_scenario(main_database, scenario)
        assert refusal.details["journal_entry_id"] == str(first.id)
        assert (
            count(
                main_database,
                "journal_entries",
                where="reference_type = 'EXPENSE' AND reference_id = :reference_id",
                reference_id=reference_id,
            )
            == 1
        )

    def test_an_unknown_reference_type_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world, reference_type="LOAN_REPAYMENT"
                    )
                )
            return refusal.value

        assert "LOAN_REPAYMENT" not in run_scenario(main_database, scenario).details["allowed"]

    def test_a_manual_adjustment_may_omit_its_reference(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            return await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_type="MANUAL_ADJUSTMENT", reference_id=None
                )
            )

        view = run_scenario(main_database, scenario)
        assert view.reference_id is None
        assert entry_row(main_database, view.id)["reversal_of_id"] is None


class TestAccountAndCurrencyValidation:
    def test_an_unknown_account_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        ghost = uuid.uuid4()

        async def scenario(service):
            with pytest.raises(ResourceNotFoundError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(ghost, debit="10", currency_id=world.base.id),
                            line(world.account("capital"), credit="10", currency_id=world.base.id),
                        ],
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"][0]["code"] == "not_found"

    def test_a_grouping_account_cannot_be_posted_to(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """A grouping account is a subtotal, not a place to put money."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(world.account("grouping"), debit="10", currency_id=world.base.id),
                            line(world.account("capital"), credit="10", currency_id=world.base.id),
                        ],
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"][0]["code"] == "not_postable"

    def test_a_deactivated_account_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """``is_active=false`` is how the system retires an account without deleting it."""
        world = build_world(api_client, admin_headers, main_database)
        from tests.accounting_helpers import create_account, unique_code

        code = unique_code()
        retired = create_account(
            api_client,
            admin_headers,
            code=code,
            name="Retired account",
            account_type="ASSET",
            is_active=False,
        )

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(uuid.UUID(retired["id"]), debit="10", currency_id=world.base.id),
                            line(world.account("capital"), credit="10", currency_id=world.base.id),
                        ],
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"][0]["code"] == "inactive"

    def test_a_line_in_the_wrong_currency_for_its_account_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """``1001 Cash USD`` may not hold afghanis: the account *is* the currency."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(world.account("cash_usd"), debit="10", currency_id=world.base.id),
                            line(world.account("capital"), credit="10", currency_id=world.base.id),
                        ],
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["fields"][0]["code"] == "currency_mismatch"
        assert refusal.details["account_currency_id"] == str(world.money("USD").id)

    def test_an_unknown_currency_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ResourceNotFoundError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            # A currency-less account: the currency lookup is what must fail
                            # here, not the account/currency relationship.
                            line(world.account("capital"), debit="10", currency_id=uuid.uuid4()),
                            line(
                                world.account("receivable"), credit="10", currency_id=uuid.uuid4()
                            ),
                        ],
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"][0]["code"] == "not_found"

    def test_a_deactivated_currency_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """A currency nobody may trade in cannot be posted, even by a direct service call."""
        from tests.accounting_helpers import create_currency, publish_rate

        world = build_world(api_client, admin_headers, main_database)
        from tests.masterdata_helpers import unique_currency_code

        created = create_currency(api_client, admin_headers, code=unique_currency_code())
        currency_id = uuid.UUID(created["id"])
        publish_rate(
            api_client,
            admin_headers,
            from_currency_id=str(currency_id),
            to_currency_id=str(world.base.id),
            buy_rate="5",
            sell_rate="6",
        )
        deactivated = api_client.patch(
            f"/api/v1/currencies/{created['id']}",
            headers=admin_headers,
            json={"is_active": False},
        )
        assert deactivated.status_code == 200, deactivated.text

        async def scenario(service):
            with pytest.raises(Exception) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(world.account("capital"), debit="10", currency_id=currency_id),
                            line(world.account("receivable"), credit="10", currency_id=currency_id),
                        ],
                    )
                )
            return refusal.value

        from app.core.exceptions import CurrencyInactiveError

        assert isinstance(run_scenario(main_database, scenario), CurrencyInactiveError)


class TestBranchValidation:
    def test_a_posting_into_another_branch_is_refused_and_audited(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """Branch isolation at the *service* layer, not merely in the UI."""
        from tests.accounting_helpers import create_branch, deactivate_branch

        world = build_world(api_client, admin_headers, main_database)
        other = create_branch(api_client, admin_headers)
        manager = world.actor(roles=(RoleName.MANAGER,))
        try:

            async def scenario(service):
                with pytest.raises(ForbiddenScopeError) as refusal:
                    # A cash movement: a document type a MANAGER may really post, so the
                    # refusal under test is the branch scope and not the permission.
                    await service.create_journal_entry(
                        **manual_entry(  # type: ignore[arg-type]
                            world,
                            actor=manager,
                            reference_type="CASH_MOVEMENT",
                            branch_id=uuid.UUID(other["id"]),
                        )
                    )
                return refusal.value

            refusal = run_scenario(main_database, scenario)
            assert refusal.details["reason"] == "ANOTHER_BRANCH"
            assert refusal.details["target_branch_id"] == other["id"]
            assert refusal.details["actor_branch_id"] == str(world.branch_id)
            denied = read(
                main_database,
                """
                SELECT new_data FROM audit_logs
                 WHERE action = :action AND new_data->>'reason' = 'ANOTHER_BRANCH'
                 ORDER BY seq DESC LIMIT 1
                """,
                action=str(AuditAction.LEDGER_POSTING_DENIED),
            )
            assert denied
            assert denied[0]["new_data"]["target_branch_id"] == other["id"]
        finally:
            deactivate_branch(api_client, admin_headers, other["id"])

    def test_an_actor_without_a_branch_cannot_post(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """``branch_id = None`` is a *restricted* state, never an unrestricted one."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ForbiddenScopeError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        actor=world.actor(
                            roles=(RoleName.MANAGER,),
                            branch_id=None,
                            permissions=["accounts.manage"],
                        ),
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["reason"] == "ACTOR_HAS_NO_BRANCH"

    def test_an_account_belonging_to_another_branch_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """Even a global-scope actor may not mix two branches' accounts in one entry."""
        from tests.accounting_helpers import (
            create_branch,
            deactivate_branch,
            load_currencies,
            scaffold_chart,
        )

        world = build_world(api_client, admin_headers, main_database)
        other = create_branch(api_client, admin_headers)
        try:
            currencies = load_currencies(main_database, [BASE_CODE])
            other_accounts, _ = scaffold_chart(
                api_client,
                admin_headers,
                branch_id=uuid.UUID(other["id"]),
                currencies=currencies,
            )

            async def scenario(service):
                with pytest.raises(ValidationError) as refusal:
                    await service.create_journal_entry(
                        **manual_entry(  # type: ignore[arg-type]
                            world,
                            lines=[
                                line(
                                    other_accounts["cash_afn"],
                                    debit="10",
                                    currency_id=world.base.id,
                                ),
                                line(
                                    world.account("capital"),
                                    credit="10",
                                    currency_id=world.base.id,
                                ),
                            ],
                        )
                    )
                return refusal.value

            refusal = run_scenario(main_database, scenario)
            assert refusal.details["fields"][0]["code"] == "branch_mismatch"
        finally:
            deactivate_branch(api_client, admin_headers, other["id"])

    def test_a_closed_branch_cannot_receive_new_postings(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        from tests.accounting_helpers import (
            create_branch,
            deactivate_branch,
            load_currencies,
            scaffold_chart,
        )

        world = build_world(api_client, admin_headers, main_database)
        branch = create_branch(api_client, admin_headers)
        currencies = load_currencies(main_database, [BASE_CODE])
        accounts, _ = scaffold_chart(
            api_client, admin_headers, branch_id=uuid.UUID(branch["id"]), currencies=currencies
        )
        deactivate_branch(api_client, admin_headers, branch["id"])

        async def scenario(service):
            with pytest.raises(ValidationError) as refusal:
                await service.create_journal_entry(
                    reference_type="MANUAL_ADJUSTMENT",
                    reference_id=uuid.uuid4(),
                    branch_id=uuid.UUID(branch["id"]),
                    lines=[
                        line(accounts["cash_afn"], debit="10", currency_id=world.base.id),
                        line(accounts["capital"], credit="10", currency_id=world.base.id),
                    ],
                    actor=world.head_actor,
                    description="posting into a retired branch",
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"] == [
            {"field": "branch_id", "code": "inactive"}
        ]

    def test_an_unknown_branch_is_refused(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            with pytest.raises(ResourceNotFoundError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world, branch_id=uuid.uuid4()
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["fields"][0]["code"] == "not_found"


class TestAuthorization:
    def test_a_posting_without_the_required_permission_is_refused_and_audited(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        reference_id = uuid.uuid4()

        async def scenario(service):
            with pytest.raises(PermissionDeniedError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=reference_id,
                        actor=world.actor(roles=()),  # a real account with no roles at all
                    )
                )
            return refusal.value

        refusal = run_scenario(main_database, scenario)
        assert refusal.details["required_permission"] == "accounts.manage"
        assert (
            count(
                main_database,
                "journal_entries",
                where="reference_id = :reference_id",
                reference_id=reference_id,
            )
            == 0
        )
        denied = read(
            main_database,
            "SELECT id, new_data FROM audit_logs WHERE action = :action ORDER BY seq DESC LIMIT 1",
            action=str(AuditAction.LEDGER_POSTING_DENIED),
        )
        assert denied, "a refused posting must leave evidence"
        assert denied[0]["new_data"]["required_permission"] == "accounts.manage"

    def test_an_entry_must_name_its_author(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)

        from tests.accounting_helpers import actor_for

        anonymous = actor_for(None, branch_id=world.branch_id, roles=(RoleName.OWNER,))

        async def scenario(service):
            with pytest.raises(PermissionDeniedError) as refusal:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        actor=anonymous,
                    )
                )
            return refusal.value

        assert run_scenario(main_database, scenario).details["reason"] == "ACTOR_REQUIRED"

    @pytest.mark.parametrize(
        ("reference_type", "role", "allowed"),
        [
            # The matrix the seeded roles really grant (PART 41 + API_CONTRACT §8):
            # ACCOUNTANT administers the books, MANAGER runs a branch, CASHIER takes money
            # at the counter, AUDITOR only reads. Deny by default for everything else.
            ("MANUAL_ADJUSTMENT", RoleName.ACCOUNTANT, True),
            ("MANUAL_ADJUSTMENT", RoleName.MANAGER, False),
            ("MANUAL_ADJUSTMENT", RoleName.CASHIER, False),
            ("MANUAL_ADJUSTMENT", RoleName.AUDITOR, False),
            ("CASH_MOVEMENT", RoleName.ACCOUNTANT, True),
            ("CASH_MOVEMENT", RoleName.MANAGER, True),
            ("CASH_MOVEMENT", RoleName.CASHIER, True),
            ("CASH_MOVEMENT", RoleName.AUDITOR, False),
            ("EXPENSE", RoleName.ACCOUNTANT, True),
            ("EXPENSE", RoleName.MANAGER, True),
            ("EXPENSE", RoleName.CASHIER, False),
            ("EXPENSE", RoleName.AUDITOR, False),
            ("EXCHANGE_TRANSACTION", RoleName.MANAGER, True),
            ("EXCHANGE_TRANSACTION", RoleName.CASHIER, True),
            ("EXCHANGE_TRANSACTION", RoleName.AUDITOR, False),
            ("TRANSFER", RoleName.CASHIER, True),
            ("TRANSFER", RoleName.AUDITOR, False),
        ],
    )
    def test_the_posted_document_type_decides_the_permission(
        self,
        api_client: TestClient,
        admin_headers: dict[str, str],
        main_database: str,
        reference_type: str,
        role: RoleName,
        allowed: bool,
    ) -> None:
        """One row per (document type, role): the matrix is the authorization contract."""
        world = build_world(api_client, admin_headers, main_database)
        actor = world.actor(roles=(role,))

        async def scenario(service):
            arguments = manual_entry(world, reference_type=reference_type)
            arguments["actor"] = actor
            try:
                await service.create_journal_entry(**arguments)  # type: ignore[arg-type]
            except PermissionDeniedError:
                return False
            return True

        assert run_scenario(main_database, scenario) is allowed


class TestTransactionAtomicity:
    """PART 20/§13: a posting is one transaction — all of it, or none of it."""

    def test_a_failure_rolls_back_the_work_of_the_same_transaction(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """The engine joins a caller's transaction: its failure takes the caller's work too.

        This is the shape Phase 5 will use — the business document, its journal entry and
        its audit rows in one transaction — so the failure must abort the *whole* unit of
        work. The proof is that the first, perfectly valid posting is gone.
        """
        world = build_world(api_client, admin_headers, main_database)
        good, bad = uuid.uuid4(), uuid.uuid4()

        async def scenario(service):
            async with service_engine_transaction(service) as session:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=good,
                        lines=[
                            line(world.account("cash_afn"), debit="500", currency_id=world.base.id),
                            line(world.account("capital"), credit="500", currency_id=world.base.id),
                        ],
                        session=session,
                    )
                )
                # The second posting fails *inside* the same transaction and the exception
                # leaves the block: that is what makes PostgreSQL abort the whole unit.
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=bad,
                        lines=[
                            line(world.account("cash_afn"), debit="500", currency_id=world.base.id),
                            line(world.account("capital"), credit="400", currency_id=world.base.id),
                        ],
                        session=session,
                    )
                )

        with pytest.raises(JournalUnbalancedError):
            run_scenario(main_database, scenario)

        assert count(main_database, "audit_logs", where="entity_id = :entry", entry=good) == 0
        for reference_id in (good, bad):
            assert (
                count(
                    main_database,
                    "journal_entries",
                    where="reference_id = :reference_id",
                    reference_id=reference_id,
                )
                == 0
            )
            assert (
                count(
                    main_database,
                    "journal_lines",
                    where=(
                        "journal_entry_id IN "
                        "(SELECT id FROM journal_entries WHERE reference_id = :reference_id)"
                    ),
                    reference_id=reference_id,
                )
                == 0
            )

    def test_a_refused_posting_leaves_no_audit_or_idempotency_row(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        key = uuid.uuid4()
        audit_before = count(main_database, "audit_logs")

        async def scenario(service):
            with pytest.raises(JournalUnbalancedError):
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        lines=[
                            line(world.account("cash_afn"), debit="10", currency_id=world.base.id),
                            line(world.account("capital"), credit="9", currency_id=world.base.id),
                        ],
                    ),
                    idempotency_key=key,
                )

        run_scenario(main_database, scenario)
        assert count(main_database, "idempotency_keys", where="key = :key", key=key) == 0
        assert count(main_database, "audit_logs") == audit_before

    def test_the_balance_cache_is_rolled_back_with_its_entry(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        """The cache is updated by a trigger in the same transaction, so it cannot leak."""
        world = build_world(api_client, admin_headers, main_database)

        async def scenario(service):
            async with service_engine_transaction(service) as session:
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=uuid.uuid4(),
                        lines=[
                            line(world.account("cash_afn"), debit="777", currency_id=world.base.id),
                            line(world.account("capital"), credit="777", currency_id=world.base.id),
                        ],
                        session=session,
                    )
                )
                raise RuntimeError("the caller's work fails after the posting")

        with pytest.raises(RuntimeError):
            run_scenario(main_database, scenario)

        cached = scalar(
            main_database,
            """
            SELECT count(*) FROM account_balances
             WHERE account_id IN (:cash, :capital)
            """,
            cash=world.account("cash_afn"),
            capital=world.account("capital"),
        )
        assert int(cached or 0) == 0

    def test_a_failed_posting_does_not_disturb_the_totals(
        self, api_client: TestClient, admin_headers: dict[str, str], main_database: str
    ) -> None:
        world = build_world(api_client, admin_headers, main_database)
        before = totals(main_database)

        async def scenario(service):
            await service.create_journal_entry(
                **manual_entry(  # type: ignore[arg-type]
                    world, reference_id=uuid.uuid4(), description="successful posting"
                )
            )
            with pytest.raises(JournalUnbalancedError):
                await service.create_journal_entry(
                    **manual_entry(  # type: ignore[arg-type]
                        world,
                        reference_id=uuid.uuid4(),
                        lines=[
                            line(world.account("cash_afn"), debit="5", currency_id=world.base.id),
                            line(world.account("capital"), credit="6", currency_id=world.base.id),
                        ],
                    )
                )

        run_scenario(main_database, scenario)
        after = totals(main_database)
        # Added with the ledger's own helper: ``before + 1000`` in this process's default
        # decimal context would round the expectation to 28 significant digits and fail
        # against a perfectly correct ledger.
        assert after == (
            money_sum([before[0], Decimal("1000")]),
            money_sum([before[1], Decimal("1000")]),
        )


# --------------------------------------------------------------------------- utilities
def service_engine_transaction(service: object) -> object:
    """The engine's transaction manager, for tests that own the boundary themselves."""
    return service._database.transaction()  # type: ignore[attr-defined]


def _lines_before(database: str) -> int:
    return count(database, "journal_lines")


def _user_id(database: str, username: str = "admin") -> uuid.UUID:
    return user_id_of(database, username)
