"""Declarative base, metadata conventions and shared column mixins.

The ORM must mirror ``docs/database/schema.sql`` exactly; the parity gate in
``tests/integration/test_schema_gate.py`` fails the build when a column, type,
nullability, key or index diverges. Constraint *expressions* (CHECK), triggers
and functions live in the database and are verified by the invariant suite
(``tests/invariants/phase0_schema_invariants.sql``) rather than duplicated here —
that keeps a single source of truth for the financial invariants.
"""

from __future__ import annotations

import datetime as dt
import uuid
from typing import Any

from sqlalchemy import DateTime, Integer, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Naming convention for objects SQLAlchemy creates. Explicitly named objects in
# the schema (all CHECK constraints, most indexes) keep their own names, which is
# what makes the parity gate able to compare them one to one.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "%(table_name)s_pkey",
}


class Base(DeclarativeBase):
    """Declarative base for every NEXUS table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:  # pragma: no cover - debugging convenience
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"

    def as_dict(self, exclude: set[str] | None = None) -> dict[str, Any]:
        """Column mapping, used by audit snapshots and the change stream."""
        excluded = exclude or {"password_hash"}
        return {
            column.name: getattr(self, column.name)
            for column in self.__table__.columns
            if column.name not in excluded
        }


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by PostgreSQL (``gen_random_uuid()``)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class CreatedAtMixin:
    """Creation timestamp, stored timezone-aware in UTC."""

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


class UpdatedAtMixin:
    """Modification timestamp maintained by the database trigger."""

    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


class VersionMixin:
    """Optimistic concurrency counter bumped by the database trigger."""

    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default=text("1"),
    )


class TimestampMixin(CreatedAtMixin, UpdatedAtMixin):
    """``created_at`` + ``updated_at``."""


def sql_now() -> dt.datetime:
    """Timezone-aware UTC now (application side; the database uses ``now()``)."""
    return dt.datetime.now(tz=dt.UTC)


def utc_timestamp() -> Any:
    """Server-side UTC timestamp expression."""
    return func.now()
