"""Journal and trial-balance response schemas (API_CONTRACT §8, PART 62).

Money crosses the wire as a **decimal string** with the stored scale
(``format_decimal`` → 10 decimals), never as a JSON number: a JSON number is parsed by
clients into a binary float, and a ledger that is exact to the last digit must not become
approximate at the edge. The schemas mirror ``AccountingService``'s payloads exactly —
there is one serializer, so a field cannot appear in one response and be missing from
another.

These models are read-only by design: Phase 4 exposes the ledger, and nothing in this
schema set can express "change a posted entry".
"""

from __future__ import annotations

import datetime as dt
import uuid

from pydantic import BaseModel, ConfigDict, Field


class JournalLineResponse(BaseModel):
    """One posted journal line, with the facts a client cannot derive."""

    model_config = ConfigDict(extra="forbid")

    id: uuid.UUID
    account_id: uuid.UUID
    account_code: str
    account_name: str
    account_type: str
    currency_id: uuid.UUID
    currency_code: str | None = None
    debit: str = Field(description="Functional (AFN) debit as a decimal string")
    credit: str = Field(description="Functional (AFN) credit as a decimal string")
    exchange_rate: str = Field(description="Functional units per unit of the line's currency")
    foreign_amount: str | None = Field(
        default=None,
        description=(
            "Physical quantity, generated by the database as (debit + credit) / exchange_rate"
        ),
    )
    description: str | None = None


class JournalEntryResponse(BaseModel):
    """One posted journal entry: header, totals, reversal linkage and its lines."""

    model_config = ConfigDict(extra="forbid")

    id: uuid.UUID
    reference_type: str
    reference_id: uuid.UUID | None = None
    description: str | None = None
    transaction_date: dt.datetime
    created_at: dt.datetime
    created_by: uuid.UUID | None = None
    created_by_username: str | None = None
    branch_id: uuid.UUID | None = None
    branch_code: str | None = None
    device_id: uuid.UUID | None = None
    reversal_of_id: uuid.UUID | None = Field(
        default=None, description="The entry this one reverses, when it is a reversal"
    )
    reversed_by_entry_id: uuid.UUID | None = Field(
        default=None, description="The entry that reverses this one, once it has been reversed"
    )
    line_count: int
    total_debit: str
    total_credit: str
    is_balanced: bool
    lines: list[JournalLineResponse] = Field(default_factory=list)


class JournalEntryListResponse(BaseModel):
    """Paginated journal listing, newest entry first."""

    model_config = ConfigDict(extra="forbid")

    items: list[JournalEntryResponse]
    total: int = Field(ge=0)
    limit: int = Field(ge=1, le=200)
    offset: int = Field(ge=0)


class TrialBalanceRowResponse(BaseModel):
    """One (account, currency) row of the trial balance."""

    model_config = ConfigDict(extra="forbid")

    account_id: uuid.UUID
    account_code: str
    account_name: str
    account_type: str
    normal_balance: str | None = None
    currency_id: uuid.UUID | None = None
    currency_code: str | None = None
    total_debit: str
    total_credit: str
    net_debit: str = Field(description="total_debit - total_credit, as v_trial_balance reports it")
    balance: str = Field(description="Signed by the account's normal balance side")
    entry_count: int


class TrialBalanceFilters(BaseModel):
    """The filters the report was generated with (API_CONTRACT §9: reports state them).

    ``from`` is a Python keyword, so the field is named ``from_`` and populated from the
    payload key ``from`` — the wire name stays what the contract promises.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    branch_id: uuid.UUID | None = None
    account_type: str | None = None
    from_: dt.datetime | None = Field(default=None, alias="from")
    to: dt.datetime | None = None
    include_inactive: bool = True


class TrialBalanceResponse(BaseModel):
    """``GET /reports/trial-balance`` — per account and currency, with its own proof."""

    model_config = ConfigDict(extra="forbid")

    source: str = Field(description="Always 'journal_lines': the immutable table behind the report")
    generated_at: dt.datetime
    filters: TrialBalanceFilters
    total_debit: str
    total_credit: str
    difference: str = Field(description="total_debit - total_credit; must be zero")
    is_balanced: bool
    rows: list[TrialBalanceRowResponse]
